### ISSUE TITLE
segmentation error

### ISSUE THREAD

**Issue by Riseryn** [kalliope-project/kalliope_neuron_wake_on_lan#3]
hello
with kalliope 0.6.0 i got this error

```
 File "resources/neurons/wake_on_lan/wake_on_lan.py", line 22, in __init__
    broadcast_address_unicode = self.broadcast_address.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'

Erreur de segmentation
```

**Comment by Sispheor** [comment]
It's an error with this neuron in particular. Please open an issue on this one.

**Comment by Sispheor** [comment]
Oh sorry, I was on my phone and I actually haven't seen that the issue was well opened on the neuron repo.
The neuron has been updated. You can delete the old version from your resources folder and give a new try.
